### ISSUE TITLE
create ephermeral file with datestamp instead of count for rollover

### ISSUE THREAD

**Issue by iankoetter** [corelight/json-streaming-logs#1]
I'm finding an error where the process watching the logs is not smart enough to understand the file was renamed and rather re-reads the entire file when it is renamed from .log to .1.log.

It might be better to initially start the file as json_streaming_conn_{ts}.log and on roll over a new file is created with the new timestamp. After N files, it starts to delete the older timestamps(in order).

This way the newest file is always the most recent timestamp, and the files themselves are never actually renamed but rather just stop being written to. 

I hope that makes sense. I'll try to hack it in and if it works properly will submit a pull request.

**Comment by sethhall** [comment]
Wow, I'm coming to this bug late.  If you're still getting email about this, what log shipper are you using that is getting confused by the rename?  From what I understand, most of these tools watch the node number which isn't changing when file rotation occurs.

**Comment by iankoetter** [comment]
Hey Seth, 
Yeah, this is old. I fixed it with some zeek scripting but at this point it feels like another lifetime ago. I think the corelight plugin basically now does what I was hacking in at the time.

Either way, I know it isn't a problem today.
Thanks!

**Comment by sethhall** [comment]
Sorry for taking so long on that.  Glad you managed to solve your 
problem at least!
